---
version: 1.0.33 # Consider updating the version number
slug: cups
name: CUPS Print Server
description: CUPS print server for network printing
url: https://github.com/ivmreg/cups-addon
codenotary: appjupiter@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
dbus: true
map:
  - data:rw
init: false
startup: services