---
version: 1.0.29
slug: cups
name: CUPS Print Server
description: CUPS print server for network printing
url: https://github.com/ivmreg/cups-addon
codenotary: appjupiter@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true # Re-enable host network mode for mDNS
dbus: true         # Grant access to the system D-Bus
map:
  - data:rw
init: false
options:
  admin_username: "admin"
  admin_password: "admin"
schema:
  admin_username: str
  admin_password: password
startup: services