---
version: "1.0.40"
slug: cups
name: CUPS Print Server
description: CUPS print server for network printing
url: https://github.com/ivmreg/cups-addon
codenotary: appjupiter@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
dbus: true
map:
  - data:rw
init: false
startup: services
ingress: true
ingress_port: 631
webui: http://[HOST]:[PORT:631]
panel_icon: mdi:printer
apparmor: true
