#!/usr/bin/with-contenv bash
set -euo pipefail

# Persistent dirs
mkdir -p /data/cups/cache /data/cups/logs /data/cups/state /data/cups/config
chown -R root:lp /data/cups
chmod -R 775 /data/cups

# Ensure system dirs
mkdir -p /etc/cups /etc/avahi/services

# Write CUPS config
cat > /data/cups/config/cupsd.conf << 'EOL'
Port 631
ServerAlias localhost
ServerAlias 127.0.0.1
ServerAlias 192.168.1.158
ServerAlias homeassistant.lan

WebInterface Yes

DefaultAuthType None
JobSheets none,none
PreserveJobHistory No

BrowseLocalProtocols dnssd

<Location />
  Order allow,deny
  Allow localhost
  Allow 192.168.1.0/24
</Location>

<Location /admin>
  Order allow,deny
  Allow localhost
  Allow 192.168.1.0/24
</Location>

<Location /jobs>
  Order allow,deny
  Allow localhost
  Allow 192.168.1.0/24
</Location>

<Limit Send-Document Send-URI Hold-Job Release-Job Restart-Job Purge-Jobs \
       Set-Job-Attributes Create-Job-Subscription Renew-Subscription \
       Cancel-Subscription Get-Notifications Reprocess-Job Cancel-Current-Job \
       Suspend-Current-Job Resume-Job Cancel-My-Jobs Close-Job CUPS-Move-Job \
       CUPS-Get-Document>
  Order allow,deny
  Allow localhost
  Allow 192.168.1.0/24
</Limit>
EOL

# # Avahi AirPrint bridge service (CUPS dnssd will publish actual queues)
# cat > /etc/avahi/services/airprint.service << 'EOL'
# <?xml version="1.0" standalone='no'?>
# <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
# <service-group>
#   <name replace-wildcards="yes">%h CUPS</name>
#   <service>
#     <type>_ipp._tcp</type>
#     <port>631</port>
#   </service>
# </service-group>
# EOL

# Link configs into system paths
ln -sf /data/cups/config/cupsd.conf /etc/cups/cupsd.conf
# # printers.conf will be generated by cupsd after lpadmin
# ln -sf /data/cups/config/printers.conf /etc/cups/printers.conf || true

# Start DBus (for Avahi) and Avahi daemon
mkdir -p /run/dbus
dbus-daemon --system --nopidfile
avahi-daemon -D

# Start cupsd in background so lpadmin can talk to it
/usr/sbin/cupsd
sleep 2

# # Register Brother HL-1110 with brlaser driver (idempotent)
# if ! lpstat -p BrotherHL1110 >/dev/null 2>&1; then
#   lpadmin -p BrotherHL1110 \
#     -E \
#     -v socket://192.168.52.167:9100 \
#     -m br1110.ppd
#   cupsenable BrotherHL1110
#   cupsaccept BrotherHL1110
# fi

# Replace background cupsd with foreground one for s6 supervision
exec /usr/sbin/cupsd -f
